// import '../../static/scss/main.scss'
import React from 'react'
import './fonts.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create snext app',
}

export default function RootLayout({
    props,
    children,
}: {
    props?: any
    children: React.ReactNode
}) {
    return <main className="main">{children}</main>
}
